language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
      - rust: nightly

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-3.7
      - libclang-3.7-dev
      - lib32z1-dev
      - libedit-dev

#install:
#    - sudo mkdir -p /usr/lib/llvm-3.7/share/llvm
#    - sudo ln -s /usr/share/llvm-3.7/cmake/ /usr/lib/llvm-3.7/share/llvm
#    - sudo ln -s /usr/bin/llvm-config-3.7 /usr/bin/llvm-config

notifications:
    email: false
