language: rust

before_install:
    # LLVM, CMake setup
    - sudo sh -c 'echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6-binaries main" >> /etc/apt/sources.list.d/llvm.list'
    - sudo sh -c 'echo "deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise main" >> /etc/apt/sources.list.d/llvm.list'
    - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test/
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get update

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq llvm-3.6 llvm-3.6-dev libedit2 libedit-dev libconfig++8-dev
    - sudo apt-get install -qq gcc-multilib

notifications:
  email: false
