[package]
name = "limonite"
version = "0.0.4"
authors = [
    "thadancardin@gmail.com",
    "thadan64@gmail.com"
]
description = "The Limonite language compiler"
repository = "https://github.com/TheDan64/limonite.git"

[[bin]]
name = "limonite"
path = "src/main.rs"

[dependencies]
docopt = "*"
env_logger = "*"
llvm_sys = "*"
log = "*"
rustc-serialize = "*"
