[package]
name = "limonite"
version = "0.0.5"
authors = [
    "thadancardin@gmail.com",
    "thadan64@gmail.com"
]
license = "Apache-2.0"
description = "The Limonite language compiler"
repository = "https://github.com/TheDan64/limonite"

[lib]
name = "limonite"
path = "src/lib.rs"

[[bin]]
name = "limonite"
path = "src/main.rs"
test = false
doc = false

[dependencies]
docopt = "*"
env_logger = "*"
llvm-sys = "*"
log = "*"
rustc-serialize = "*"

[[test]]
name = "tests"
